function [data] = Dati(test)
%=======================================================================================================
% TEMPLATE OF THE STRUCT DATI
%=======================================================================================================
%
%  DATA= struct(    'name',                 % (string: 'TestHigham' or 'TestSmorzato') set the name of the test
%                    'x',                   % (vector of double) training input points of the neural network
%                    'y',                   % (vector of double) training outputs of the neural network
%                    'shape',               % (vector of double) number of
%                                           neurons for every layer (n1,n2,n3,..)
%                    'L',                   % (int) depth of the neural network
%                    'sigma',               % (function handle) activation function of every neuron
%                    'sigmaprime',          % (function handle) derivative of the activation function
%                    'Maxiter',             % (int) maximum number of computations of the gradient
%                    'threshold',           % (double) threshold over the cost function to stop the method
%                    'batchsize_gradient',  % (int) number of points in the batch for the GD/SGD
%                    'eta',                 % (double) learning rate for GD/SGD
%                    'batchsize_coarse',    % (int) number of points in the batch of the coarse operator
%                    'batchsize_fine',      % (int) number of points in the batch of the fine operator
%                    'n_coarse',            % (int) maximum number of refinements associated to the coarse operator
%                    'n_fine',              % (int) number of refinements associated to the fine operator
%                    'dT',                  % (double) learning rate for the coarse operator
%                    'dt',                  % (double) learning rate for the fine operator
%                    );
%========================================================================================================


if strcmp(test,'TestHigham')
    data = struct( 'name',             test,...
                   ... % Test name
                   'x',               [0.1,0.3,0.1,0.6,0.4,0.6,0.5,0.9,0.4,0.7; ...
                                       0.1,0.4,0.5,0.9,0.2,0.3,0.6,0.2,0.4,0.6],...
                   ...%training input points of the neural network
                   'y',               [ones(1,5) zeros(1,5); zeros(1,5) ones(1,5)],...
                   ...%training outputs of the neural network
                   'shape',           [2,3,3,2],...
                   ...%shape of the neural network
                   'L',               4,...
                   ...%depth of the neural network
                   'sigma',           @(x) 1./(1+exp(-x)),...
                   ...%activation function of every neuron
                   'sigmaprime',      @(x) 1./(1+exp(-x)).^2.*(exp(-x)),...
                   ...%derivative of the activation function
                   'Maxiter',         2e6,...
                   ...%maximum number of computations of the gradient
                   'threshold',       1e-2,...
                   ...% threshold over the cost function to stop the method
                   'batchsize_gradient',1,...
                   ...%size of the batch for the GD/SGD
                   'eta',             0.01,...
                   ...%learning rate for GD/SGD
                   'batchsize_coarse',  10,...
                   ...%size of the batch of the coarse operator
                   'batchsize_fine',   1,...
                   ...%size of the batch of the fine operator
                   'n_coarse',        200,...
                   ...%maximum number of refinements associated to the coarse operator
                   'n_fine',          60,...
                   ...%number of refinements associated to the fine operator
                   'dT',              0.01*60,...
                   ...%learning rate for the coarse operator
                   'dt',              0.01 ...
                   ...%learning rate for the fine operator
                   );
elseif strcmp(test,'TestSmorzato')
    data = struct( 'name',             test,...
                   ... % Test name
                   'x',               linspace(0,10,30),...
                   ...%training input points of the neural network
                   'y',               exp(-linspace(0,10,30)).*sin(linspace(0,10,30)),...
                   ...%training outputs of the neural network
                   'shape',           [1,16,16,1],...
                   ...%shape of the neural network
                   'L',               4,...
                   ...%depth of the neural network
                   'sigma',           @(x) 1./(1+exp(-x)),...
                   ...%activation function of every neuron
                   'sigmaprime',      @(x) 1./(1+exp(-x)).^2.*(exp(-x)),...
                   ...%derivative of the activation function
                   'Maxiter',         1e4,...
                   ...%maximum number of computations of the gradient
                   'threshold',       1e-2,...
                   ...% threshold over the cost function to stop the method
                  'batchsize_gradient',1,...
                   ...%size of the batch for the GD/SGD
                   'eta',             0.01,...
                   ...%learning rate for GD/SGD
                   'batchsize_coarse', 30,...
                   ...%size of the batch of the coarse operator
                   'batchsize_fine',  1,...
                   ...%size of the batch of the fine operator
                   'n_coarse',        100,...
                   ...%maximum number of refinements associated to the coarse operator
                   'n_fine',          10,...
                   ...%number of refinements associated to the fine operator
                   'dT',              0.1*10,...
                   ...%learning rate for the coarse operator
                   'dt',              0.1 ...
                   ...%learning rate for the fine operator
                   );
end
end
